### PR TITLE
Improved Perst stability, i.e. db is corrupted in less number of cases. 	ZooDb (https://github.com/tzaeschke/zoodb) added as possible persistent engine. PersistentEngineBase class added as predecessor of all engine implementations. 	Firefox 54 problem with not showing checkboxes fixed. PerstToZoodb migration added. CORS and ETAG filters added. Dependecies updated to the recent versions. CodeMirror upgraded to 5.25.2; zk Vbox replaced by Vlayout.

### PR DESCRIPTION
**Pull request by slavap**

### CODE REVIEW

**Comment by ghaseminya** [comment]
Hi @slavap 
get a link of your deployed version.

**Comment by slavap** [comment]
@ghaseminya you’d better merge it, not close it. ZooDB as database proved itself as super reliable, I’m using it in production for more than an year, and luckily forgot all this corruption problems I was regularly getting with Perst.

**Comment by ghaseminya** [comment]
Hi @slavap 
Sorry, i closed this PR, because this PR for 2 years ago, and i guess that deprecated your change.
I read your change and merge it.

**Comment by ghaseminya** [comment]
Thanks for @slavap to add migration readme file ;)

**Pull request merged**
